#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
intensity_normalization.exec.gmm_normalize

command line executable for gmm intensity normalization routine

Author: Jacob Reinhold (jacob.reinhold@jhu.edu)
Created on: May 08, 2018
"""

from __future__ import print_function, division

import argparse
from glob import glob
import logging
import os
import sys
import warnings

import numpy as np

with warnings.catch_warnings():
    warnings.filterwarnings('ignore', category=FutureWarning)
    from intensity_normalization.errors import NormalizationError
    from intensity_normalization.normalize import gmm
    from intensity_normalization.utilities import io
    from intensity_normalization.utilities.mask import gmm_class_mask, background_mask


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-i', '--image', type=str, required=True,
                        help='path to a nifti MR image of the brain')
    parser.add_argument('-m', '--brain-mask', type=str,
                        help='path to a nifti brain mask for the image, '
                             'provide this if image is not skull-stripped')
    parser.add_argument('-o', '--output-dir', type=str, default=None,
                        help='path to output normalized images '
                             '(default: to directory containing images)')
    parser.add_argument('-b', '--background-mask', type=str,
                        help='path to a mask of the background')
    parser.add_argument('-w', '--wm-peak', type=str, default=None,
                        help='saved WM peak value, found by first input T1 image,'
                             'can be used consecutively for other contrasts for the same patient')
    parser.add_argument('--save-wm-peak', action='store_true', default=False,
                        help='store the found WM peak or nah, use wm-peak as the name if true')
    parser.add_argument('--find-background-mask', action='store_true', default=False,
                        help='calculate a mask for the background (to zero it out)')
    parser.add_argument('--norm-value', type=float, default=1000,
                        help='value by which to normalize the WM peak')
    parser.add_argument('--contrast', type=str, choices=['t1', 't2'], default='t1',
                        help='pick the contrast of the input MR image (t1 or t2)')
    parser.add_argument('--keep-bg', action='store_true', default=False,
                        help='if this flag is activated, then no background mask '
                             'is calculated or used')
    parser.add_argument('--dir', action='store_true', default=False,
                        help='image and mask are directories, not individual images')
    parser.add_argument('-v', '--verbosity', action="count", default=0,
                        help="increase output verbosity (e.g., -vv is more than -v)")
    args = parser.parse_args()
    return args


def process(image, brain_mask, args, logger):
    img = io.open_nii(image)
    mask = io.open_nii(brain_mask)
    dirname, base, ext = io.split_filename(image)
    if args.output_dir is not None:
        dirname = args.output_dir
        if not os.path.exists(dirname):
            logger.info('Making output directory: {}'.format(dirname))
            os.mkdir(dirname)
    if args.find_background_mask:
        bg_mask = background_mask(img)
        bgfile = os.path.join(dirname, base + '_bgmask' + ext)
        io.save_nii(bg_mask, bgfile, is_nii=True)
    if args.wm_peak is not None:
        logger.info('Loading WM peak: ', args.wm_peak)
        peak = float(np.load(args.wm_peak))
    else:
        peak = gmm_class_mask(img, brain_mask=mask, contrast=args.contrast)
        if args.save_wm_peak:
            np.save(os.path.join(dirname, base + '_wmpeak.npy'), peak)
    normalized = gmm.gmm_normalize(img, mask, args.norm_value, args.contrast,
                                   args.background_mask, peak)
    outfile = os.path.join(dirname, base + '_norm' + ext)
    logger.info('Normalized image saved: {}'.format(outfile))
    io.save_nii(normalized, outfile, is_nii=True)


def main():
    args = parse_args()
    if args.verbosity == 1:
        level = logging.getLevelName('INFO')
    elif args.verbosity >= 2:
        level = logging.getLevelName('DEBUG')
    else:
        level = logging.getLevelName('WARNING')
    logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=level)
    logger = logging.getLogger(__name__)
    try:
        if args.dir:
            if not os.path.isdir(args.image) or not os.path.isdir(args.brain_mask):
                raise NormalizationError('if dir option on, then image and brain-mask must be directories')
            img_fns = sorted(glob(os.path.join(args.image, '*.nii*')))
            mask_fns = sorted(glob(os.path.join(args.brain_mask, '*.nii*')))
            if len(img_fns) != len(mask_fns) and len(img_fns) > 0:
                raise NormalizationError('input images and masks must be in correspondence and greater than zero '
                                         '({:d} != {:d})'.format(len(img_fns), len(mask_fns)))
            for i, (img, mask) in enumerate(zip(img_fns, mask_fns), 1):
                _, base, _ = io.split_filename(img)
                logger.info('Normalizing image {} ({:d}/{:d})'.format(img, i, len(img_fns)))
                process(img, mask, args, logger)
        else:
            if not os.path.isfile(args.image) or not os.path.isfile(args.brain_mask):
                raise NormalizationError('if dir option off, then image and brain-mask must be files')
            process(args.image, args.brain_mask, args, logger)
        return 0
    except Exception as e:
        logger.exception(e)
        return 1


if __name__ == '__main__':
    sys.exit(main())
