#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
intensity_normalization.exec.kde_normalize

command line executable for kernel density intensity normalization routine

Author: Jacob Reinhold (jacob.reinhold@jhu.edu)
Created on: May 08, 2018
"""

from __future__ import print_function, division

import argparse
import logging
import os
import sys

from intensity_normalization.normalize import kde
from intensity_normalization.utilities import io


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-i', '--image', type=str, required=True)
    parser.add_argument('-m', '--brain-mask', type=str, default=None)
    parser.add_argument('-c', '--contrast', type=str, default='T1')
    parser.add_argument('--norm-value', type=float, default=1000)
    parser.add_argument('-v', '--verbosity', action="count",
                        help="increase output verbosity (e.g., -vv is more than -v)")
    args = parser.parse_args()
    return args


def main():
    args = parse_args()
    if args.verbosity == 1:
        level = logging.getLevelName('INFO')
    elif args.verbosity == 2:
        level = logging.getLevelName('DEBUG')
    else:
        level = logging.getLevelName('WARNING')
    logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=level)
    logger = logging.getLogger(__name__)
    try:
        img = io.open_nii(args.image)
        if args.brain_mask is not None:
            mask = io.open_nii(args.brain_mask)
        else:
            mask = None
        dirname, base, _ = io.split_filename(args.image)
        normalized = kde.kde_normalize(img, mask, args.norm_value)
        outfile = os.path.join(dirname, base + '_norm.nii.gz')
        io.save_nii(normalized, outfile, is_nii=True)
        return 0
    except Exception as e:
        logger.exception(e)
        return 1


if __name__ == '__main__':
    sys.exit(main())
