#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
intensity_normalization.exec.ravel_normalize

command line executable for RAVEL intensity normalization routine

Author: Jacob Reinhold (jacob.reinhold@jhu.edu)
Created on: May 08, 2018
"""

import sys

from intensity_normalization.normalize.ravel import main


if __name__ == "__main__":
    sys.exit(main())
