#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
intensity_normalization.exec.ws-normalize

command line executable for whitestripe intensity normalization routine

Author: Jacob Reinhold (jacob.reinhold@jhu.edu)

Created on: May 08, 2018
"""

from __future__ import print_function, division

import argparse
import logging
import sys
import warnings

with warnings.catch_warnings():
    warnings.filterwarnings('ignore', category=FutureWarning)
    from intensity_normalization.normalize import whitestripe


def arg_parser():
    parser = argparse.ArgumentParser(description='Use WhiteStripe to normalize a set nifti MR images of the brain')
    parser.add_argument('-i', '--img-dir', type=str, required=True,
                        help = 'path to directory with images to be processed '
                               '(should all be of one contrast)')
    parser.add_argument('-c', '--contrast', type=str, default='T1', choices=['T1', 'T2', 'FLAIR'],
                        help='contrast of the images in img-dir')
    parser.add_argument('-m', '--mask-dir', type=str, default=None,
                        help='if images are not skull-stripped, directory for '
                             'corresponding brain masks for img-dir (not intelligently sorted, '
                             'so ordering must be consistent in directory)')
    parser.add_argument('-o', '--output-dir', type=str, default=None,
                        help='if you want the normalized images saved in a particular location,'
                             'provide that directory here (must already exist)')
    parser.add_argument('--slices', default=None, nargs=2, type=int,
                        help='this argument is used in WhiteStripe, it uses the provided'
                             'slice range to extract a region by which to normalize the histogram'
                             'of the entire image (e.g., "--slices 50 61" uses slices 50-60')
    parser.add_argument('-v', '--verbosity', action="count", default=0,
                        help="increase output verbosity (e.g., -vv is more than -v)")
    return parser


def main():
    args = arg_parser().parse_args()
    if args.verbosity == 1:
        level = logging.getLevelName('INFO')
    elif args.verbosity >= 2:
        level = logging.getLevelName('DEBUG')
    else:
        level = logging.getLevelName('WARNING')
    logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=level)
    logger = logging.getLogger(__name__)
    try:
        _ = whitestripe.ws_normalize(args.img_dir, args.contrast, args.mask_dir, args.output_dir, slices=args.slices)
        return 0
    except Exception as e:
        logger.exception(e)
        return 1


if __name__ == "__main__":
    sys.exit(main())
