#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
intensity_normalization.exec.ws_normalize

command line executable for whitestripe intensity normalization routine

Author: Jacob Reinhold (jacob.reinhold@jhu.edu)
Created on: May 08, 2018
"""

from __future__ import print_function, division

import argparse
import logging
import sys

from intensity_normalization.normalize import whitestripe


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-i', '--img-dir', type=str, required=True,
                        help = 'path to directory with images to be processed '
                               '(should all be of one contrast)')
    parser.add_argument('-c', '--contrast', type=str, default='T1',
                        help='contrast of the images in img-dir')
    parser.add_argument('-m', '--mask-dir', type=str, default=None,
                        help='if images are not skull-stripped, directory for '
                             'corresponding brain masks for img-dir (not intelligently sorted, '
                             'so ordering must be consistent in directory)')
    parser.add_argument('-o', '--output-dir', type=str, default=None,
                        help='if you want the normalized images saved in a particular location,'
                             'provide that directory here (must already exist)')
    parser.add_argument('--slices', type=tuple, default=(80,120),
                        help='this argument is used in WhiteStripe, it uses the provided'
                             'slice range to extract a region by which to normalize the histogram'
                             'of the entire image')
    parser.add_argument('-v', '--verbosity', action="count",
                        help="increase output verbosity (e.g., -vv is more than -v)")
    args = parser.parse_args()
    return args


def main():
    args = parse_args()
    if args.verbosity == 1:
        level = logging.getLevelName('INFO')
    elif args.verbosity >= 2:
        level = logging.getLevelName('DEBUG')
    else:
        level = logging.getLevelName('WARNING')
    logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=level)
    logger = logging.getLogger(__name__)
    try:
        _ = whitestripe.ws_normalize(args.img_dir, args.contrast, args.mask_dir, args.output_dir, slices=args.slices)
        return 0
    except Exception as e:
        logger.exception(e)
        return 1


if __name__ == "__main__":
    sys.exit(main())
