blank_issues_enabled: false
contact_links:
  - name: Question/Help/Support
    url: https://github.com/jcreinhold/intensity-normalization/discussions
    about: "All general questions should be posted to 'Discussions'."
